export const START_BUTTON_TEXT = 'Start';

export const PAUSE_BUTTON_TEXT = 'Pause';

export const LIST_CURRENT_TIMER = {
  POMODORO_MODE: 'pomodoro-mode',
  SHORT_BREAK_MODE: 'short-break-mode',
  LONG_BREAK_MODE: 'long-break-mode'
};

export const RADIX_DECIMAL = 10;

export const POMODORO_TIMES = {
  WORK_ONE_POMODORO_MINUTES: 25,
  BREAK_SHORT_MINUTES: 5,
  BREAK_LONG_MINUTES: 15,
  ONE_HOUR_IN_MINUTE: 60,
  MINUTE_IN_MILLISECONDS: 60000
};

export const TIMER_DEFAULT_TIMES = {
  [LIST_CURRENT_TIMER.POMODORO_MODE]: `${POMODORO_TIMES.WORK_ONE_POMODORO_MINUTES}:00`,
  [LIST_CURRENT_TIMER.SHORT_BREAK_MODE]: `0${POMODORO_TIMES.BREAK_SHORT_MINUTES}:00`,
  [LIST_CURRENT_TIMER.LONG_BREAK_MODE]: `${POMODORO_TIMES.BREAK_LONG_MINUTES}:00`
};
